services:
    marttiphpbb.calendarmonoinput.listener:
        class: marttiphpbb\calendarmonoinput\event\listener
        arguments:
            - '@marttiphpbb.calendarmonoinput.posting'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarmonoinput.posting:
        class: marttiphpbb\calendarmonoinput\service\posting
        arguments:
            - '@service_container'
            - '@marttiphpbb.calendarmonoinput.store'
            - '@auth'
            - '@language'
            - '@ext.manager'
            - '@request'
            - '@dispatcher'

    marttiphpbb.calendarmonoinput.store:
        class: marttiphpbb\calendarmonoinput\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'
