services:
    marttiphpbb.calendarinput.listener:
        class: marttiphpbb\calendarinput\event\listener
        arguments:
            - '@request'
            - '@language'
            - '@marttiphpbb.calendarinput.posting'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarinput.posting:
        class: marttiphpbb\calendarinput\service\posting
        arguments:
            - '@service_container'
            - '@marttiphpbb.calendarinput.store'
            - '@template'
            - '@language'
            - '@ext.manager'

    marttiphpbb.calendarinput.store:
        class: marttiphpbb\calendarinput\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'
