services:
    marttiphpbb.calendarinput.main_listener:
        class: marttiphpbb\calendarinput\event\main_listener
        arguments:
            - '@template'
            - '@language'
            - '@config'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarinput.posting_listener:
        class: marttiphpbb\calendarinput\event\posting_listener
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@marttiphpbb.calendarinput.render.input_range'
            - '@marttiphpbb.calendarinput.render.posting'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarinput.core.event_container:
        class: marttiphpbb\calendarinput\core\event_container
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '%tables.topics%'

    marttiphpbb.calendarinput.timeformat:
        class: marttiphpbb\calendarinput\util\timeformat
        arguments:
            - '@user'

    marttiphpbb.calendarinput.render.input_range:
        class: marttiphpbb\calendarinput\render\input_range
        arguments:
            - '@marttiphpbb.calendarinput.store'
            - '@template'

    marttiphpbb.calendarinput.render.posting:
        class: marttiphpbb\calendarinput\render\posting
        arguments:
            - '@marttiphpbb.calendarinput.store'
            - '@template'
            - '@language'

    marttiphpbb.calendarinput.dateformat:
        class: marttiphpbb\calendarinput\util\dateformat
        arguments:
            - '@user'
            - '@language'

    marttiphpbb.calendarinput.store:
        class: marttiphpbb\calendarinput\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'
